{
 "title": "Sensoren",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "500ms",
 "panels": [
  {
   "title": "System information",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "* **Host name**: {{hostname}}\n* **Platform**: {{platform}}\n* **Architecture**: {{architecture}}\n* **Processor**: {{processor}}\n* **OS version**: {{osVersion}}\n* **Boot time**: {{bootTime}}\n* **System time**: {{systemTime}}"
   },
   "targets": [
    { "expr": "system_info" }
   ]
  },
  {
   "title": "System metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cpuTemperature", "legendFormat": "CPU Temperature" },
    { "expr": "cpuUsage", "legendFormat": "CPU usage" },
    { "expr": "freeRam", "legendFormat": "Free RAM" },
    { "expr": "freeDiskSpace", "legendFormat": "Free disk space" }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "speed" }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "Distance from ultrasonic sensor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "cm" }
   ],
   "targets": [
    { "expr": "distance", "legendFormat": "Distance" }
   ]
  }
 ]
}