version: "3.8"
services:
    grafana:
        image: grafana/grafana
        ports:
            - "80:3000"
        volumes:
            - "./grafana/config:/etc/grafana/provisioning"
            - "./grafana/dashboards:/var/lib/grafana/dashboards"
        links:
            - prometheus
        environment:
            GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 1ms
        restart: unless-stopped
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus:/etc/prometheus
        links:
            - distance
        restart: unless-stopped
    distance:
        build: ./distance
        privileged: true
        restart: unless-stopped
    temperature-humidity:
        build: ./temperature-humidity
        privileged: true
        restart: unless-stopped
